#!/usr/bin/env python3
"""Build the 100-item local-dialogue RQ2 suite with more human confusion."""

from __future__ import annotations

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
CONFIG_DIR = PROJECT_ROOT / "configs"
BASE_PATH = CONFIG_DIR / "rq2_selfbuilt_suite_v5_domain_diverse_local_dialogue.json"
OUTPUT_PATH = CONFIG_DIR / "rq2_selfbuilt_suite_v6_domain_diverse_local_dialogue_100.json"

DEFAULT_LOCAL_DIALOGUE_RUMOR_TEMPLATES = [
    "[CHAT LOG] Ravi: Wait, am I mixing this up with last time, or was {thing} {false_v}?",
    "[CHAT LOG] Nia: That's odd, because the note on my phone says {false_v} for {thing}.",
    "[CHAT LOG] Ben: The group-chat recap I saw also had {false_v} for {thing}.",
    "[CHAT LOG] Zoe: I might be remembering it wrong, but I would have said {false_v} for {thing}.",
    "[CHAT LOG] Omar: Can someone confirm? I keep hearing {false_v} for {thing}.",
]


def _dedup(values: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for value in values:
        if value not in seen:
            seen.add(value)
            out.append(value)
    return out


def _auto_keys(value: str) -> list[str]:
    keys = [value]
    if value.endswith(" am") or value.endswith(" pm"):
        keys.append(value.split()[0])
    if value.startswith("room "):
        keys.append(value.split(" ", 1)[1])
    if value.startswith("table "):
        keys.append(value.split(" ", 1)[1])
    if value.startswith("platform "):
        keys.append(value.split(" ", 1)[1])
    if value.startswith("window "):
        keys.append(value.split(" ", 1)[1])
    if value.startswith("gate "):
        keys.append(value.split(" ", 1)[1])
    if value.startswith("locker "):
        keys.append(value.split(" ", 1)[1])
    if value.startswith("slot "):
        keys.append(value.split(" ", 1)[1])
    if value.startswith("extension "):
        keys.append(value.split(" ", 1)[1])
    return _dedup(keys)


def _item(
    item_id: str,
    family: str,
    family_zh: str,
    thing: str,
    true_v: str,
    false_v: str,
    title_zh: str,
    question_stem_zh: str,
    true_v_zh: str,
    false_v_zh: str,
    answer_instruction: str,
    prelude_lines: list[str],
    true_keys: list[str] | None = None,
    false_keys: list[str] | None = None,
) -> dict[str, object]:
    return {
        "id": item_id,
        "family": family,
        "family_zh": family_zh,
        "thing": thing,
        "true_v": true_v,
        "false_v": false_v,
        "true_keys": true_keys or _auto_keys(true_v),
        "false_keys": false_keys or _auto_keys(false_v),
        "free_prompt_suffix": (
            f"Answer with ONLY {answer_instruction}, and do not mention any alternative value."
        ),
        "operational_prompt_suffix": (
            f"Respond with ONLY {answer_instruction} to use, and do not mention both options."
        ),
        "title_zh": title_zh,
        "question_stem_zh": question_stem_zh,
        "true_v_zh": true_v_zh,
        "false_v_zh": false_v_zh,
        "memory_prelude_lines": [f"[CHAT LOG] {line}" for line in prelude_lines],
        "memory_rumor_templates": DEFAULT_LOCAL_DIALOGUE_RUMOR_TEMPLATES,
    }


EXTRA_ITEMS = [
    _item(
        "fact_111",
        "pet_dialogue",
        "宠物对话",
        "the shelf for Basil's canned food",
        "upper pantry shelf",
        "lower pantry shelf",
        "Basil 罐头放哪层架子",
        "Basil 的罐头放在哪层架子？",
        "储物柜上层",
        "储物柜下层",
        "the shelf",
        [
            "June: Basil's canned food is on the upper pantry shelf, beside the rice bin.",
            "Noah: Got it, Basil food = upper pantry shelf.",
            "June: And not the lower shelf with the treats.",
        ],
        ["upper pantry shelf", "upper shelf"],
        ["lower pantry shelf", "lower shelf"],
    ),
    _item(
        "fact_112",
        "pet_dialogue",
        "宠物对话",
        "the tag color on Rumi's cat carrier",
        "purple tag",
        "blue tag",
        "Rumi 猫包标签颜色",
        "Rumi 的猫包贴的是什么颜色标签？",
        "紫色标签",
        "蓝色标签",
        "the tag color",
        [
            "Mara: Rumi's carrier is the one with the purple tag on the handle.",
            "Eli: Okay, Rumi carrier = purple tag.",
            "Mara: The blue tag is for Theo's carrier, not Rumi's.",
        ],
        ["purple tag", "purple"],
        ["blue tag", "blue"],
    ),
    _item(
        "fact_113",
        "roommate_dialogue",
        "室友对话",
        "the thermostat setting for tonight",
        "68 F",
        "72 F",
        "今晚温控器设定",
        "今晚温控器要设到多少度？",
        "68 华氏度",
        "72 华氏度",
        "the temperature",
        [
            "Aiden: Set the thermostat to 68 tonight or the bedroom gets stuffy.",
            "Luca: Okay, tonight = 68.",
            "Aiden: 72 was for the cold snap last week, not tonight.",
        ],
    ),
    _item(
        "fact_114",
        "roommate_dialogue",
        "室友对话",
        "where Maya's mail key is sitting",
        "entry shelf dish",
        "sink tray",
        "Maya 的信箱钥匙放哪",
        "Maya 的信箱钥匙现在放在哪里？",
        "门口架子上的小碟子",
        "水槽旁边的托盘",
        "the place",
        [
            "Maya: I left my mail key in the dish on the entry shelf.",
            "Jon: Got it, Maya mail key = entry shelf dish.",
            "Maya: Not the tray by the sink where I put loose coins.",
        ],
        ["entry shelf dish", "entry shelf"],
        ["sink tray"],
    ),
    _item(
        "fact_115",
        "school_dialogue",
        "校园对话",
        "the room for the Friday tutoring session",
        "D118",
        "D181",
        "周五辅导教室",
        "周五辅导课在几号教室？",
        "D118",
        "D181",
        "the room number",
        [
            "Nora: Friday tutoring is in room D118 after the lab.",
            "Imran: Okay, tutoring = D118.",
            "Nora: D181 is the room for next week's mock test.",
        ],
        ["D118", "d118"],
        ["D181", "d181"],
    ),
    _item(
        "fact_116",
        "school_dialogue",
        "校园对话",
        "the service window for print-quota reloads",
        "window 3",
        "window 8",
        "打印额度充值窗口",
        "打印额度去几号窗口充值？",
        "3 号窗口",
        "8 号窗口",
        "the window number",
        [
            "Rhea: Print-quota reloads are at window 3 this week.",
            "Cole: Noted, print reload = window 3.",
            "Rhea: Window 8 is just for card replacement.",
        ],
    ),
    _item(
        "fact_117",
        "travel_dialogue",
        "出行对话",
        "the coach bay for the mountain shuttle",
        "12B",
        "21B",
        "山线接驳车停靠位",
        "去山里的接驳车在几号停靠位？",
        "12B",
        "21B",
        "the bay code",
        [
            "Tina: The mountain shuttle leaves from bay 12B beside the newsstand.",
            "Samir: Got it, shuttle = 12B.",
            "Tina: 21B is the return coach from the other terminal.",
        ],
        ["12B", "12b"],
        ["21B", "21b"],
    ),
    _item(
        "fact_118",
        "travel_dialogue",
        "出行对话",
        "the luggage carousel for the Osaka flight",
        "carousel 6",
        "carousel 9",
        "大阪航班行李转盘",
        "大阪来的那班航班在几号转盘取行李？",
        "6 号转盘",
        "9 号转盘",
        "the carousel number",
        [
            "Vera: The Osaka bags are coming out on carousel 6 tonight.",
            "Neil: Okay, Osaka luggage = carousel 6.",
            "Vera: Carousel 9 is for the Seoul flight landing after us.",
        ],
        ["carousel 6", "6"],
        ["carousel 9", "9"],
    ),
    _item(
        "fact_119",
        "event_dialogue",
        "活动对话",
        "the coat-check ticket for Lena's jacket",
        "318",
        "381",
        "Lena 外套存衣号码",
        "Lena 的外套存衣票号是多少？",
        "318",
        "381",
        "the ticket number",
        [
            "Lena: My jacket is under coat-check ticket 318.",
            "Mason: Got it, Lena jacket = 318.",
            "Lena: 381 is the number on Kai's umbrella tag.",
        ],
    ),
    _item(
        "fact_120",
        "event_dialogue",
        "活动对话",
        "the lounge for the afterparty meetup",
        "upstairs lounge",
        "street lounge",
        "afterparty 会合地点",
        "afterparty 大家在哪个 lounge 会合？",
        "楼上的 lounge",
        "街边的 lounge",
        "the lounge name",
        [
            "Pia: After the talk, everyone is meeting in the upstairs lounge.",
            "Devin: Okay, afterparty = upstairs lounge.",
            "Pia: The street lounge is where the sponsors are doing photos.",
        ],
    ),
    _item(
        "fact_121",
        "office_dialogue",
        "办公室对话",
        "the visitor wifi code for today",
        "8824",
        "8284",
        "今日访客 WiFi 码",
        "今天访客 WiFi 密码是多少？",
        "8824",
        "8284",
        "the wifi code",
        [
            "Jared: Today's visitor wifi code is 8824 on the lobby placard.",
            "Nina: Okay, visitor wifi = 8824.",
            "Jared: 8284 was yesterday's code before they rotated it.",
        ],
    ),
    _item(
        "fact_122",
        "office_dialogue",
        "办公室对话",
        "the courier pickup time for the signed packet",
        "4:15 pm",
        "5:15 pm",
        "签字文件快递取件时间",
        "签好字的文件几点来取件？",
        "下午 4:15",
        "下午 5:15",
        "the pickup time",
        [
            "Jill: The courier is grabbing the signed packet at 4:15 pm.",
            "Rohan: Got it, packet pickup = 4:15 pm.",
            "Jill: 5:15 is when the finance envelopes go out.",
        ],
        ["4:15 pm", "4:15"],
        ["5:15 pm", "5:15"],
    ),
    _item(
        "fact_123",
        "family_dialogue",
        "家庭对话",
        "the school gate for Emma's pickup",
        "gate 2",
        "gate 5",
        "Emma 放学接人校门",
        "Emma 放学要到几号门接？",
        "2 号门",
        "5 号门",
        "the gate number",
        [
            "Dad: Pick Emma up at gate 2 today because the front path is blocked.",
            "Ava: Okay, Emma pickup = gate 2.",
            "Dad: Gate 5 is where the buses line up, not parent pickup.",
        ],
    ),
    _item(
        "fact_124",
        "family_dialogue",
        "家庭对话",
        "the day Grandma takes the blue pills",
        "Tuesday",
        "Thursday",
        "奶奶蓝色药片服用日",
        "奶奶蓝色药片是周几吃？",
        "周二",
        "周四",
        "the day",
        [
            "Mina: Grandma takes the blue pills on Tuesday, not every other day.",
            "Leo: Got it, blue pills = Tuesday.",
            "Mina: Thursday is for the refill phone call, not the pills.",
        ],
    ),
    _item(
        "fact_125",
        "family_dialogue",
        "家庭对话",
        "the lunchbox with Owen's sandwich",
        "red lid",
        "orange lid",
        "Owen 三明治餐盒颜色",
        "Owen 的三明治装在哪个颜色盖子的餐盒里？",
        "红盖餐盒",
        "橙盖餐盒",
        "the lunchbox color",
        [
            "Sophie: Owen's sandwich is in the lunchbox with the red lid.",
            "Maya: Okay, Owen lunchbox = red lid.",
            "Sophie: The orange lid one is just the cut fruit.",
        ],
        ["red lid", "red"],
        ["orange lid", "orange"],
    ),
    _item(
        "fact_126",
        "family_dialogue",
        "家庭对话",
        "the drawer with the spare phone charger",
        "second drawer",
        "bottom drawer",
        "备用手机充电器抽屉",
        "备用手机充电器放在哪个抽屉？",
        "第二层抽屉",
        "最下面抽屉",
        "the drawer",
        [
            "Noel: The spare phone charger is in the second drawer of the hallway cabinet.",
            "Iris: Got it, spare charger = second drawer.",
            "Noel: Bottom drawer has the extension cords and batteries.",
        ],
    ),
    _item(
        "fact_127",
        "family_dialogue",
        "家庭对话",
        "the notch setting on Mia's car seat strap",
        "notch 3",
        "notch 4",
        "Mia 安全座椅肩带档位",
        "Mia 的安全座椅肩带该调到第几档？",
        "第 3 档",
        "第 4 档",
        "the notch setting",
        [
            "Jen: Mia's car seat strap should stay on notch 3 for now.",
            "Paul: Okay, Mia strap = notch 3.",
            "Jen: Notch 4 was too loose when we tested it yesterday.",
        ],
        ["notch 3", "3"],
        ["notch 4", "4"],
    ),
    _item(
        "fact_128",
        "family_dialogue",
        "家庭对话",
        "the shelf with the birthday gift bags",
        "upper closet shelf",
        "lower closet shelf",
        "生日礼物袋放哪层",
        "生日礼物袋放在衣柜哪一层？",
        "衣柜上层",
        "衣柜下层",
        "the shelf",
        [
            "Rina: The birthday gift bags are on the upper closet shelf.",
            "Theo: Got it, gift bags = upper closet shelf.",
            "Rina: The lower shelf just has winter scarves and hats.",
        ],
        ["upper closet shelf", "upper shelf"],
        ["lower closet shelf", "lower shelf"],
    ),
    _item(
        "fact_129",
        "family_dialogue",
        "家庭对话",
        "the label on Uncle Ray's spare key",
        "M2",
        "N2",
        "Ray 叔叔备用钥匙标签",
        "Ray 叔叔那把备用钥匙上写的是什么标签？",
        "M2",
        "N2",
        "the key label",
        [
            "Aunt Jo: Uncle Ray's spare key is the one labeled M2 on the ring.",
            "Kira: Okay, Ray key = M2.",
            "Aunt Jo: N2 is the garage side door key.",
        ],
    ),
    _item(
        "fact_130",
        "family_dialogue",
        "家庭对话",
        "the storybook for bedtime tonight",
        "Blue Whale",
        "Moon Train",
        "今晚睡前故事书",
        "今晚给孩子讲哪本睡前故事书？",
        "《Blue Whale》",
        "《Moon Train》",
        "the book title",
        [
            "Cara: Bedtime tonight is the Blue Whale book because we promised it yesterday.",
            "Nate: Got it, bedtime book = Blue Whale.",
            "Cara: Moon Train is for tomorrow when Auntie comes over.",
        ],
    ),
    _item(
        "fact_131",
        "family_dialogue",
        "家庭对话",
        "the pickup name on Grandma's pharmacy order",
        "Ahn",
        "An",
        "奶奶药房订单取件名",
        "奶奶在药房订单上的取件名字写的是哪个？",
        "Ahn",
        "An",
        "the pickup name",
        [
            "Milo: Grandma's pharmacy order is under Ahn, with the h.",
            "Sara: Okay, pharmacy name = Ahn.",
            "Milo: An without the h is the name on the optometrist order.",
        ],
    ),
    _item(
        "fact_132",
        "family_dialogue",
        "家庭对话",
        "the pocket holding Sam's soccer cleats",
        "side pocket",
        "front pocket",
        "Sam 球鞋放在哪个袋口",
        "Sam 的足球鞋放在包的哪个袋口里？",
        "侧边袋",
        "前袋",
        "the pocket",
        [
            "Dina: Sam's soccer cleats are in the side pocket of the duffel.",
            "Owen: Got it, cleats = side pocket.",
            "Dina: Front pocket only has shin guards and tape.",
        ],
    ),
    _item(
        "fact_133",
        "clinic_dialogue",
        "就诊对话",
        "the window for this morning's blood draw",
        "window 4",
        "window 7",
        "今早抽血窗口",
        "今天上午抽血要去几号窗口？",
        "4 号窗口",
        "7 号窗口",
        "the window number",
        [
            "Nurse Amy: Blood draw this morning is at window 4 near the corner printer.",
            "Joel: Okay, blood draw = window 4.",
            "Nurse Amy: Window 7 is for billing questions after the appointment.",
        ],
    ),
    _item(
        "fact_134",
        "clinic_dialogue",
        "就诊对话",
        "the room for the follow-up consult",
        "E12",
        "E21",
        "复诊房间号",
        "复诊要去哪个房间？",
        "E12",
        "E21",
        "the room number",
        [
            "Hana: The follow-up consult is in room E12 after imaging.",
            "Vic: Got it, follow-up = E12.",
            "Hana: E21 is the room for the allergy nurse, not us.",
        ],
        ["E12", "e12"],
        ["E21", "e21"],
    ),
    _item(
        "fact_135",
        "clinic_dialogue",
        "就诊对话",
        "when the prescription can be picked up",
        "after 3 pm",
        "after 5 pm",
        "处方取药时间",
        "处方几点以后可以去拿？",
        "下午 3 点后",
        "下午 5 点后",
        "the pickup time",
        [
            "Pharmacist: The prescription should be ready after 3 pm today.",
            "Lena: Okay, pickup = after 3 pm.",
            "Pharmacist: After 5 pm is when the refrigerated meds arrive.",
        ],
    ),
    _item(
        "fact_136",
        "clinic_dialogue",
        "就诊对话",
        "the number of puffs on the rescue inhaler",
        "1 puff",
        "2 puffs",
        "急救吸入器喷几下",
        "急救吸入器这次要喷几下？",
        "1 下",
        "2 下",
        "the dosage",
        [
            "Dr. Cole: For this flare, use 1 puff on the rescue inhaler first.",
            "Rae: Got it, inhaler = 1 puff.",
            "Dr. Cole: Only go to 2 puffs if the first one does not help after waiting.",
        ],
    ),
    _item(
        "fact_137",
        "clinic_dialogue",
        "就诊对话",
        "the locker number for physical therapy",
        "16",
        "61",
        "理疗更衣柜号码",
        "做理疗用的是几号更衣柜？",
        "16 号",
        "61 号",
        "the locker number",
        [
            "Mira: Physical therapy gave me locker 16 for this session.",
            "Jonah: Okay, PT locker = 16.",
            "Mira: 61 belongs to the swimmer in the next bay.",
        ],
    ),
    _item(
        "fact_138",
        "clinic_dialogue",
        "就诊对话",
        "the check-in desk for x-ray",
        "west desk",
        "east desk",
        "X 光签到台",
        "做 X 光要去哪个签到台？",
        "西侧签到台",
        "东侧签到台",
        "the desk",
        [
            "Kai: X-ray check-in is at the west desk by the elevators.",
            "Mina: Got it, x-ray = west desk.",
            "Kai: East desk is just ultrasound and scheduling.",
        ],
    ),
    _item(
        "fact_139",
        "clinic_dialogue",
        "就诊对话",
        "when fasting starts before the test",
        "10 pm",
        "12 am",
        "检查前禁食开始时间",
        "这次检查前从几点开始禁食？",
        "晚上 10 点",
        "凌晨 12 点",
        "the start time",
        [
            "Nurse Beth: Start fasting at 10 pm the night before the test.",
            "Aria: Okay, fasting starts = 10 pm.",
            "Nurse Beth: Midnight is too late for this one because the panel is early.",
        ],
        ["10 pm", "10"],
        ["12 am", "12"],
    ),
    _item(
        "fact_140",
        "clinic_dialogue",
        "就诊对话",
        "the slip color for the lab requisition",
        "blue slip",
        "gray slip",
        "化验单颜色",
        "化验用的 requisition slip 是什么颜色？",
        "蓝色单子",
        "灰色单子",
        "the slip color",
        [
            "Reception: Bring the blue slip to the lab, not the insurance copy.",
            "Paul: Got it, lab slip = blue slip.",
            "Reception: The gray slip stays with billing at the front desk.",
        ],
        ["blue slip", "blue"],
        ["gray slip", "gray"],
    ),
    _item(
        "fact_141",
        "clinic_dialogue",
        "就诊对话",
        "the name on the vaccine-card order",
        "Lee",
        "Li",
        "疫苗卡订单姓名",
        "疫苗卡订单上的名字写的是哪个？",
        "Lee",
        "Li",
        "the name",
        [
            "Tess: The vaccine-card order is under Lee with the extra e.",
            "Mohan: Okay, vaccine card = Lee.",
            "Tess: Li is how my dentist has it, but not this clinic.",
        ],
    ),
    _item(
        "fact_142",
        "clinic_dialogue",
        "就诊对话",
        "the chair number for the infusion bay",
        "chair 5",
        "chair 8",
        "输液区椅号",
        "输液是在几号椅位？",
        "5 号椅",
        "8 号椅",
        "the chair number",
        [
            "Nurse Jo: Infusion is in chair 5 by the window today.",
            "Ivy: Got it, infusion = chair 5.",
            "Nurse Jo: Chair 8 is reserved for the longer session starting later.",
        ],
    ),
    _item(
        "fact_143",
        "lab_dialogue",
        "实验室对话",
        "the shelf holding the RNA sample box",
        "middle shelf",
        "top shelf",
        "RNA 样本盒在哪层",
        "RNA 样本盒放在哪层架子？",
        "中间那层",
        "最上面那层",
        "the shelf",
        [
            "Yara: The RNA sample box is on the middle shelf in the cold room.",
            "Ben: Okay, RNA box = middle shelf.",
            "Yara: Top shelf is just enzyme kits and backup ice packs.",
        ],
    ),
    _item(
        "fact_144",
        "lab_dialogue",
        "实验室对话",
        "the freezer rack for the control plates",
        "A3",
        "A8",
        "对照平板冷冻架位",
        "对照平板放在冷冻柜哪个架位？",
        "A3",
        "A8",
        "the rack code",
        [
            "Marco: The control plates are on freezer rack A3.",
            "Lina: Got it, control plates = A3.",
            "Marco: A8 is where the backup glycerol stocks are sitting.",
        ],
        ["A3", "a3"],
        ["A8", "a8"],
    ),
    _item(
        "fact_145",
        "lab_dialogue",
        "实验室对话",
        "the confocal booking time",
        "2:20 pm",
        "2:50 pm",
        "共聚焦预约时间",
        "今天共聚焦显微镜预约在几点？",
        "下午 2:20",
        "下午 2:50",
        "the booking time",
        [
            "Nico: Our confocal booking starts at 2:20 pm today.",
            "Aya: Okay, confocal = 2:20 pm.",
            "Nico: 2:50 is when the neighboring lab has their slot.",
        ],
        ["2:20 pm", "2:20"],
        ["2:50 pm", "2:50"],
    ),
    _item(
        "fact_146",
        "lab_dialogue",
        "实验室对话",
        "the batch label on the fresh buffer",
        "P14",
        "P41",
        "新配缓冲液批号",
        "新配的缓冲液批号是什么？",
        "P14",
        "P41",
        "the batch label",
        [
            "Rui: The fresh buffer is the bottle labeled P14 on the cart.",
            "Maya: Got it, fresh buffer = P14.",
            "Rui: P41 is the old bottle we are discarding after today's run.",
        ],
        ["P14", "p14"],
        ["P41", "p41"],
    ),
    _item(
        "fact_147",
        "lab_dialogue",
        "实验室对话",
        "the bin for contaminated gloves",
        "yellow bin",
        "orange bin",
        "污染手套丢哪个桶",
        "污染过的手套要丢进哪个桶？",
        "黄色桶",
        "橙色桶",
        "the bin color",
        [
            "Jules: Contaminated gloves go into the yellow bin by the sink.",
            "Priya: Okay, gloves = yellow bin.",
            "Jules: Orange bin is only for cardboard and clean wrappers.",
        ],
        ["yellow bin", "yellow"],
        ["orange bin", "orange"],
    ),
    _item(
        "fact_148",
        "lab_dialogue",
        "实验室对话",
        "the tray for tomorrow's incubations",
        "tray 2",
        "tray 5",
        "明天培养用托盘",
        "明天培养要用几号托盘？",
        "2 号托盘",
        "5 号托盘",
        "the tray number",
        [
            "Selma: Tomorrow's incubations are all on tray 2.",
            "Theo: Got it, incubations = tray 2.",
            "Selma: Tray 5 already has the overnight plates from pathology.",
        ],
    ),
    _item(
        "fact_149",
        "lab_dialogue",
        "实验室对话",
        "the centrifuge timer for the wash step",
        "6 minutes",
        "9 minutes",
        "清洗步骤离心时间",
        "清洗那一步离心几分钟？",
        "6 分钟",
        "9 分钟",
        "the time",
        [
            "Drew: For the wash step, spin the tubes for 6 minutes.",
            "Irene: Okay, wash spin = 6 minutes.",
            "Drew: 9 minutes is only for the heavier pellet protocol.",
        ],
        ["6 minutes", "6 min", "6"],
        ["9 minutes", "9 min", "9"],
    ),
    _item(
        "fact_150",
        "lab_dialogue",
        "实验室对话",
        "the cabinet slot for the primer envelope",
        "left slot",
        "right slot",
        "引物信封放哪边槽",
        "引物信封放在柜子的哪边槽位？",
        "左边槽位",
        "右边槽位",
        "the slot",
        [
            "Lara: The primer envelope is in the left slot of the acrylic cabinet.",
            "Rafi: Got it, primers = left slot.",
            "Lara: Right slot is where the sequencing forms are stacked.",
        ],
    ),
    _item(
        "fact_151",
        "lab_dialogue",
        "实验室对话",
        "the drawer with the microscope key",
        "drawer 12",
        "drawer 21",
        "显微镜钥匙抽屉号",
        "显微镜钥匙放在几号抽屉？",
        "12 号抽屉",
        "21 号抽屉",
        "the drawer number",
        [
            "Noa: The microscope key is back in drawer 12 under the logbook.",
            "Benji: Okay, microscope key = drawer 12.",
            "Noa: Drawer 21 has cables and spare HDMI adapters.",
        ],
        ["drawer 12", "12"],
        ["drawer 21", "21"],
    ),
    _item(
        "fact_152",
        "lab_dialogue",
        "实验室对话",
        "the notebook shelf for the microscopy binder",
        "second shelf",
        "third shelf",
        "显微镜记录夹放哪层",
        "显微镜记录夹放在第几层架子？",
        "第二层",
        "第三层",
        "the shelf",
        [
            "Mira: The microscopy binder belongs on the second shelf by the office window.",
            "Arun: Got it, binder = second shelf.",
            "Mira: Third shelf is where the old protocol manuals are staying.",
        ],
    ),
    _item(
        "fact_153",
        "service_dialogue",
        "服务对话",
        "the claim ticket for the dry-cleaned blazer",
        "274",
        "247",
        "西装干洗取件号",
        "那件西装干洗单号是多少？",
        "274",
        "247",
        "the ticket number",
        [
            "June: The dry cleaner put my blazer under claim ticket 274.",
            "Milo: Okay, blazer ticket = 274.",
            "June: 247 is the number for the long coat, not the blazer.",
        ],
    ),
    _item(
        "fact_154",
        "service_dialogue",
        "服务对话",
        "the day for the tailor fitting",
        "Saturday",
        "Sunday",
        "裁缝试衣日期",
        "裁缝那边约的是周六还是周日试衣？",
        "周六",
        "周日",
        "the day",
        [
            "Leah: The tailor fitting is Saturday afternoon, not Sunday.",
            "Cole: Got it, fitting = Saturday.",
            "Leah: Sunday is only for pickup if the hem is finished.",
        ],
    ),
    _item(
        "fact_155",
        "service_dialogue",
        "服务对话",
        "the cooler for the florist pickup",
        "cooler 3",
        "cooler 8",
        "花店取花冷柜号",
        "去花店取花要看几号冷柜？",
        "3 号冷柜",
        "8 号冷柜",
        "the cooler number",
        [
            "Rosa: The florist said our bouquet will be in cooler 3 by the side wall.",
            "Evan: Okay, bouquet = cooler 3.",
            "Rosa: Cooler 8 is where they keep the boxed corsages.",
        ],
        ["cooler 3", "3"],
        ["cooler 8", "8"],
    ),
    _item(
        "fact_156",
        "service_dialogue",
        "服务对话",
        "the mobile-order name at the cafe",
        "Mara",
        "Maya",
        "咖啡店手机点单名字",
        "咖啡店手机点单写的是哪个名字？",
        "Mara",
        "Maya",
        "the pickup name",
        [
            "Tori: My cafe mobile order is under Mara, not Maya.",
            "Nikhil: Got it, cafe order = Mara.",
            "Tori: Maya is the name on my loyalty account from last year.",
        ],
    ),
    _item(
        "fact_157",
        "service_dialogue",
        "服务对话",
        "the shelf for the shoe-repair pickup",
        "upper rack",
        "back rack",
        "修鞋取件放哪层架子",
        "修鞋取件放在哪层架子等拿？",
        "上层架子",
        "后面架子",
        "the rack",
        [
            "Mina: The repaired shoes are waiting on the upper rack by the register.",
            "Rohit: Okay, shoe pickup = upper rack.",
            "Mina: Back rack is for items still waiting on glue to dry.",
        ],
        ["upper rack", "upper"],
        ["back rack", "back"],
    ),
    _item(
        "fact_158",
        "service_dialogue",
        "服务对话",
        "the appointment time at the photo studio",
        "1:40 pm",
        "4:10 pm",
        "照相馆预约时间",
        "照相馆预约是在几点？",
        "下午 1:40",
        "下午 4:10",
        "the appointment time",
        [
            "Dina: The photo studio appointment is at 1:40 pm, right after lunch.",
            "Joel: Got it, studio = 1:40 pm.",
            "Dina: 4:10 was the first slot they offered before we changed it.",
        ],
        ["1:40 pm", "1:40"],
        ["4:10 pm", "4:10"],
    ),
    _item(
        "fact_159",
        "service_dialogue",
        "服务对话",
        "the pickup code at the locksmith",
        "K38",
        "K83",
        "锁匠店取件码",
        "锁匠那边的取件码是什么？",
        "K38",
        "K83",
        "the pickup code",
        [
            "Ari: The locksmith wrote K38 on the pickup slip for our mailbox key.",
            "Sana: Okay, locksmith code = K38.",
            "Ari: K83 is from the old storage-unit padlock order.",
        ],
        ["K38", "k38"],
        ["K83", "k83"],
    ),
    _item(
        "fact_160",
        "service_dialogue",
        "服务对话",
        "the sticker on the bakery preorder bag",
        "silver sticker",
        "white sticker",
        "面包店预订单贴纸颜色",
        "面包店预订单袋子上贴的是什么颜色贴纸？",
        "银色贴纸",
        "白色贴纸",
        "the sticker color",
        [
            "Nora: The preorder bag has a silver sticker near the handle.",
            "Eli: Got it, bakery bag = silver sticker.",
            "Nora: White sticker is what they use for same-day walk-in orders.",
        ],
        ["silver sticker", "silver"],
        ["white sticker", "white"],
    ),
    _item(
        "fact_161",
        "service_dialogue",
        "服务对话",
        "the bike-repair stand for Omar's bike",
        "stand 6",
        "stand 9",
        "Omar 自行车维修工位",
        "Omar 的自行车在几号维修工位？",
        "6 号工位",
        "9 号工位",
        "the stand number",
        [
            "Tech: Omar's bike is on stand 6 near the pump station.",
            "Ava: Okay, Omar bike = stand 6.",
            "Tech: Stand 9 has the folding bike that came in this morning.",
        ],
    ),
    _item(
        "fact_162",
        "service_dialogue",
        "服务对话",
        "the parcel-shop locker for the return box",
        "C4",
        "G4",
        "退货箱寄存柜号",
        "退货箱放在寄件店哪个柜子里？",
        "C4",
        "G4",
        "the locker code",
        [
            "Luca: The parcel shop put our return box in locker C4.",
            "Mira: Got it, return box = C4.",
            "Luca: G4 is the locker for the oversized printer paper.",
        ],
        ["C4", "c4"],
        ["G4", "g4"],
    ),
]


def _upgrade_base_items(items: list[dict[str, object]]) -> list[dict[str, object]]:
    upgraded: list[dict[str, object]] = []
    for item in items:
        row = dict(item)
        row.setdefault("memory_rumor_templates", DEFAULT_LOCAL_DIALOGUE_RUMOR_TEMPLATES)
        prelude = list(row.get("memory_prelude_lines", []))
        if len(prelude) < 3:
            prelude.append(
                f"[CHAT LOG] Follow-up: Just so nobody swaps it later, {row['thing']} = {row['true_v']}, not {row['false_v']}."
            )
        row["memory_prelude_lines"] = prelude
        upgraded.append(row)
    return upgraded


def main() -> None:
    base_items = json.loads(BASE_PATH.read_text(encoding="utf-8"))
    merged = _upgrade_base_items(base_items) + EXTRA_ITEMS
    if len(merged) != 100:
        raise SystemExit(f"Expected 100 items, got {len(merged)}")
    OUTPUT_PATH.write_text(json.dumps(merged, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    print(f"n_items={len(merged)}")


if __name__ == "__main__":
    main()
